name: dotted_decoration
description: Dotted line decoration is handly package to draw dotted divider, dotted border for rectangle, circle or rounded rectangle.
version: 2.0.0
homepage: https://github.com/mdalameen/dotted_decoration

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
